#!/usr/bin/env bash

USAGE="[ssh options] <remote> [command]"
. $(git --exec-path)/git-sh-setup

_getRemoteHost () {
  case $1 in
    git+ssh://*) echo "$1" | cut -d/ -f3;;
    ssh://*)     echo "$1" | cut -d/ -f3;;
    *:*)         echo "$1" | cut -d: -f1;;
  esac
}

_getRemoteDirectory () {
  case $1 in
    git+ssh://*) echo "$1" | cut -d/ -f4-;;
    ssh://*)     echo "$1" | cut -d/ -f4-;;
    *:*)         echo "$1" | cut -d: -f2;;
  esac
}

_sshcd () {
  ssh "$(_getRemoteHost "$remote_url")" $ssh_opts $ssh_tty "cd '"$(_getRemoteDirectory "$remote_url")"' && $@"
  exit $?
}

remote="$1"; shift
test -z "$remote" && usage
remote_url=$(git config remote."$remote".url)
case "$remote_url" in
  '')
    die "Could not find url for $remote"
    ;;
  file://*|https://*|https://*|git://*)
    die "Protocol not supported: ${remote_url%%://}"
    ;;
esac

ssh_opts=""
ssh_tty=""
while true
do
  case $1 in
    -1|-2|-4|-6|-A|-a|-C|-f|-g|-K|-k|-M|-N|-n|-q|-s|-V|-v|-X|-x|-Y|-y)
      ssh_opts="$ssh_opts $1"
      shift
      ;;
    -b|-c|-D|-e|-F|-I|-i|-L|-l|-m|-O|-o|-p|-R|-S|-W|-w)
      ssh_opts="$ssh_opts $1 $2"
      shift
      shift
      ;;
    -t|-T)
      ssh_tty="$1"
      shift
      ;;
    '')
      ssh_tty=${ssh_tty:--t}
      _sshcd "exec "'${SHELL:-/bin/bash}'
      ;;
    *)
      _sshcd "$@"
      ;;
  esac
done
